desc = "OpenCore Configuration File Auto Download"
[[FirmwareDrivers]]
name = "HfsPlus.efi"
update_strategy = "by_file_commit_history"
owner = "acidanthera"
repo = "OcBinaryData"
path = "Drivers/HfsPlus.efi"
commit_date = 2021-11-01T17:17:40

[[FirmwareDrivers]]
name = "OpenRuntime.efi"
update_strategy = "in_oc_release"
path = "X64/EFI/OC/Drivers/OpenRuntime.efi"

[[ACPI]]
name = "EC-USBX"
update_strategy = "by_file_commit_history"
owner = "dortania"
repo = "Getting-Started-With-ACPI"
path = "extra-files/compiled/SSDT-EC-USBX-DESKTOP.aml"
commit_date = 2021-02-02T23:47:48

[Basic]
fresh_update = true
cpu_core = 12

[SSDT]
owner = "dortania"
repo = "Getting-Started-With-ACPI"
path = "extra-files/compiled/SSDT-EC-USBX-DESKTOP.aml"

[OpenCore]
owner = "acidanthera"
repo = "OpenCorePkg"
macVersion = "Monterey"
publish_date = 2022-04-18T10:43:22

[EFI_DIR]
boot = "BOOT"
oc = "OC"
acpi = "OC/ACPI"
drivers = "OC/Drivers"
kexts = "OC/Kexts"
resources = "OC/Resources"
tools = "OC/Tools"

[AMDKernelPatch]
owner = "AMD-OSX"
repo = "AMD_Vanilla"
path = "patches.plist"
commit_date = 1900-01-01T00:00:00Z

[Kexts.VirtualSMC]
kextType = "MustHave"
owner = "acidanthera"
repo = "VirtualSMC"
publish_date = 2022-03-07T17:40:19

[Kexts.Lilu]
kextType = "MustHave"
owner = "acidanthera"
repo = "Lilu"
publish_date = 2022-02-07T17:41:37

[Kexts.WhateverGreen]
kextType = "Graphics"
name = "WhateverGreen"
owner = "acidanthera"
repo = "WhateverGreen"
publish_date = 2022-03-07T17:40:49

[Kexts.AppleALC]
kextType = "Audio"
owner = "acidanthera"
repo = "AppleALC"
publish_date = 2022-04-18T15:57:36

[Kexts.SmallTreeIntel82576]
kextType = "Ethernet"
owner = "khronokernel"
repo = "SmallTree-I211-AT-patch"
publish_date = 1900-01-01T00:00:00Z
enable = false

[Kexts.LucyRTL8125Ethernet]
kextType = "Ethernet"
owner = "Mieze"
repo = "LucyRTL8125Ethernet"
publish_date = 2021-04-29T18:54:39

[Kexts.AirportItlwm]
kextType = "WiFi"
owner = "OpenIntelWireless"
repo = "itlwm"
publish_date = 2022-01-01T00:50:04

[Kexts.IntelBluetoothFirmware]
kextType = "Bluetooth"
owner = "OpenIntelWireless"
repo = "IntelBluetoothFirmware"
publish_date = 1900-01-01T00:00:00Z

[Kexts.BrcmPatchRAM]
kextType = "Bluetooth"
owner = "acidanthera"
repo = "BrcmPatchRAM"
publish_date = 1900-01-01T00:00:00Z

[Kexts.AppleMCEReporterDisabler]
kextType = "Extras"
browserDownloadUrl = "https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip"
publish_date = 1900-01-01T00:00:00Z

[Kexts.NVMeFix]
kextType = "Extras"
owner = "acidanthera"
repo = "NVMeFix"
publish_date = 1900-01-01T00:00:00Z

[Kexts.RestrictEvents]
kextType = "Extras"
owner = "acidanthera"
repo = "RestrictEvents"
publish_date = 1900-01-01T00:00:00Z

[Kexts.SMCAMDProcessor]
kextType = "CPU"
owner = "trulyspinach"
repo = "SMCAMDProcessor"
publish_date = 2021-07-30T13:23:04
