desc = "黑苹果系统安装包配置"
[[FirmwareDrivers]]
name = "HfsPlus.efi"
update_strategy = "by_file_commit_history"
owner = "acidanthera"
repo = "OcBinaryData"
path = "Drivers/HfsPlus.efi"
commit_date = 2021-11-01T17:17:40Z

[[FirmwareDrivers]]
name = "OpenRuntime.efi"
update_strategy = "in_oc_release"
path = "X64/EFI/OC/Drivers/OpenRuntime.efi"

[Kexts.VirtualSMC]
kextType = "MustHave"
owner = "acidanthera"
repo = "VirtualSMC"
publish_date = 1900-01-01T00:00:00Z

[Kexts.Lilu]
kextType = "MustHave"
owner = "acidanthera"
repo = "Lilu"
publish_date = 1900-01-01T00:00:00Z

[Kexts.WhateverGreen]
kextType = "Graphics"
name = "WhateverGreen"
owner = "acidanthera"
repo = "WhateverGreen"
publish_date = 1900-01-01T00:00:00Z

[Kexts.AppleALC]
kextType = "Audio"
owner = "acidanthera"
repo = "AppleALC"
publish_date = 1900-01-01T00:00:00Z

[Kexts.SmallTreeIntel82576]
kextType = "Ethernet"
owner = "khronokernel"
repo = "SmallTree-I211-AT-patch"
publish_date = 1900-01-01T00:00:00Z

[Kexts.LucyRTL8125Ethernet]
kextType = "Ethernet"
owner = "Mieze"
repo = "LucyRTL8125Ethernet"
publish_date = 1900-01-01T00:00:00Z

[Kexts.AirportItlwm]
kextType = "WiFi"
owner = "OpenIntelWireless"
repo = "itlwm"
published_at = 1900-01-01T00:50:04Z

[Kexts.IntelBluetoothFirmware]
kextType = "Bluetooth"
owner = "OpenIntelWireless"
repo = "IntelBluetoothFirmware"
publish_date = 1900-01-01T00:00:00Z

[Kexts.BrcmPatchRAM]
kextType = "Bluetooth"
owner = "acidanthera"
repo = "BrcmPatchRAM"
publish_date = 1900-01-01T00:00:00Z

[Kexts.AppleMCEReporterDisabler]
kextType = "Extras"
browserDownloadUrl = "https://github.com/acidanthera/bugtracker/files/3703498/AppleMCEReporterDisabler.kext.zip"
publish_date = 1900-01-01T00:00:00Z

[Kexts.NVMeFix]
kextType = "Extras"
owner = "acidanthera"
repo = "NVMeFix"
publish_date = 1900-01-01T00:00:00Z

[SSDT]
owner = "dortania"
repo = "Getting-Started-With-ACPI"
path = "extra-files/compiled/SSDT-EC-USBX-DESKTOP.aml"

[OpenCore]
owner = "acidanthera"
repo = "OpenCorePkg"
macVersion = "Monterey"
publish_date = 2022-04-18T10:43:22Z

[EFI_DIR]
boot = "BOOT"
oc = "OC"
acpi = "OC/ACPI"
drivers = "OC/Drivers"
kexts = "OC/Kexts"
resources = "OC/Resources"
tools = "OC/Tools"
